#Verify that all country is visible and clickable

from selenium import webdriver
import random
import time
import unittest
from selenium.webdriver import Keys
from selenium.webdriver.common.by import By
from selenium.common.exceptions import WebDriverException, TimeoutException
from selenium.webdriver.support.wait import WebDriverWait
import helpers as hp
from selenium.webdriver.support import expected_conditions as EC

class ChromeSearch(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()

    #Check that the current url is correct

        driver2 = self.driver
        driver2.get(hp.url)
        time.sleep(2)

        # Random delay function:
        def delay():
            time.sleep(random.randint(1, 5))
            delay()

        Apple_Expected_Url = hp.url
        current_url = driver2.current_url
        if current_url == Apple_Expected_Url:
            print("The currect URL is correct:", driver2.current_url)
        else:
            print("The current url is error:", driver2.current_url)

        # Check that the Apple title is correct
        Apple_Expected_Title = "Apple"
        current_title = driver2.title
        if Apple_Expected_Title == current_title:
            print("The Apple TITLE is correct:", driver2.title)
        else:
            print("The Apple TITLE is error:", driver2.title)

    def test_Africa_Middle_East_and_India(self):
        driver = self.driver
        driver.maximize_window()
        driver.get(hp.url)
        time.sleep(2)
        wait = WebDriverWait(driver, 5)
        # Africa, Middle East, and India
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bahrain)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bahrain)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bahrain_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bahrain_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Botswana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Botswana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cameroun)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cameroun)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Republique_Centrafricaine)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Republique_Centrafricaine)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cote_d_Ivoire)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cote_d_Ivoire)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Egypt)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Egypt)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Egypt_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Egypt_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinea_Bissau)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinea_Bissau)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinee)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinee)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinee_Equatoriale)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinee_Equatoriale)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_India)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_India)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Israel)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Israel)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jordan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jordan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jordan_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jordan_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kenya)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kenya)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kuwait)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kuwait)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kuwait_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kuwait_arab)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Madagascar)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Madagascar)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mali)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mali)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Maroc)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Maroc)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Maurice)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Maurice)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mozambique)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mozambique)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Niger)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Niger)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nigeria)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nigeria)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Oman)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Oman)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Oman_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Oman_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Qatar)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Qatar)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Qatar_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Qatar_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Saudi_Arabia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Saudi_Arabia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Saudi_Arabia_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Saudi_Arabia_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Senegal)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Senegal)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_South_Africa)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_South_Africa)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Tunisie)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Tunisie)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uganda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uganda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Arab_Emirates)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Arab_Emirates)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Arab_Emirates_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Arab_Emirates_arab)))
        time.sleep(2)
        print("Africa, Middle East, and India visible and clickable -  PASSED")

        # Asia Pacific
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Australia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Australia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_China_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_China_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hong_Kong)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hong_Kong)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hong_Kong_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hong_Kong_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Indonesia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Indonesia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Japan_ja)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Japan_ja)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Korea_ko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Korea_ko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Macao_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Macao_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Malaysia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Malaysia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_New_Zealand)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_New_Zealand)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Philippines)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Philippines)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Singapore)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Singapore)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Taiwan_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Taiwan_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Thailand_th)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Thailand_th)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Vietnam_vi)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Vietnam_vi)))
        time.sleep(2)
        print("Asia Pacific visible and clickable -  PASSED")

        # Europe
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Armenia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Armenia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Azerbaijan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Azerbaijan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belarus)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belarus)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belgie)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belgie)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belgique)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belgique)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bulgary)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bulgary)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cesko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cesko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Danmark)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Danmark)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Deutschland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Deutschland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Eesti)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Eesti)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Espana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Espana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_France)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_France)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Georgia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Georgia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Greece)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Greece)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hrvatska)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hrvatska)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ireland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ireland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Italia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Italia)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kazakhstan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kazakhstan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kyrgyzstan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kyrgyzstan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Latvija)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Latvija)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Liechtenstein)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Liechtenstein)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Lietuva)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Lietuva)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Luxembourg)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Luxembourg)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Magyarorszag)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Magyarorszag)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Malta)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Malta)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Moldova)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Moldova)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Montenegro)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Montenegro)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nederland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nederland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_North_Macedonia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_North_Macedonia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Norge)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Norge)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Osterreich)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Osterreich)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Polska)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Polska)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Portugal)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Portugal)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Romania)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Romania)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Russia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Russia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Slovensko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Slovensko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Slovenia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Slovenia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Schweiz)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Schweiz)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suisse)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suisse)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suomi)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suomi)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Sverige)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Sverige)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Tajikistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Tajikistan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turkiye)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turkiye)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turkmenistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turkmenistan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Kingdom)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Kingdom)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ukraine)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ukraine)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uzbekistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uzbekistan)))
        print("Europe is visible and clickable -  PASSED")
        time.sleep(2)

        # Latin America and the Caribbean
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Anguilla)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Anguilla)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Antigua_Barbuda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Antigua_Barbuda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Argentina)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Argentina)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Barbados)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Barbados)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belize)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belize)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bermuda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bermuda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bolivia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bolivia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Brasil)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Brasil)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_British_Virgin_Islands)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_British_Virgin_Islands)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cayman_Islands)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cayman_Islands)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Chile)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Chile)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Colombia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Colombia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Costa_Rica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Costa_Rica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Dominica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Dominica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Republica_Dominicana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Republica_Dominicana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ecuador)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ecuador)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_El_Salvador)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_El_Salvador)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Grenada)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Grenada)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guatemala)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guatemala)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guyana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guyana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Honduras)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Honduras)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jamaica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jamaica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mexico)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mexico)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Montserrat)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Montserrat)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nicaragua)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nicaragua)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Panama)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Panama)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Paraguay)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Paraguay)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Peru)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Peru)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Kitts_Nevis)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Kitts_Nevis)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Lucia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Lucia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Vincent_The_Grenadines)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Vincent_The_Grenadines)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suriname)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suriname)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_The_Bahamas)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_The_Bahamas)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Trinidad_Tobago)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Trinidad_Tobago)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turks_Caicos)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turks_Caicos)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uruguay)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uruguay)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Venezuela)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Venezuela)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_America_Latina_y_el_Caribe_Es)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_America_Latina_y_el_Caribe_Es)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Latin_America_and_the_Caribbean_Eng)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Latin_America_and_the_Caribbean_Eng)))
        time.sleep(2)

        # The United States, Canada, and Puerto Rico
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Canada_English)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Canada_English)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Canada_Francais)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Canada_Francais)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Puerto_Rico_English)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Puerto_Rico_English)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Puerto_Rico_Espanol)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Puerto_Rico_Espanol)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.United_States)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.United_States)))
        time.sleep(2)

class FirefoxSearch(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.maximize_window()

    #Check that the current url is correct

        driver2 = self.driver
        driver2.get(hp.url)
        time.sleep(2)

        # Random delay function:
        def delay():
            time.sleep(random.randint(1, 5))
            delay()

        Apple_Expected_Url = hp.url
        current_url = driver2.current_url
        if current_url == Apple_Expected_Url:
            print("The currect URL is correct:", driver2.current_url)
        else:
            print("The current url is error:", driver2.current_url)

        # Check that the Apple title is correct
        Apple_Expected_Title = "Apple"
        current_title = driver2.title
        if Apple_Expected_Title == current_title:
            print("The Apple TITLE is correct:", driver2.title)
        else:
            print("The Apple TITLE is error:", driver2.title)

    def test_Africa_Middle_East_and_India(self):
        driver = self.driver
        driver.maximize_window()
        driver.get(hp.url)
        time.sleep(2)
        wait = WebDriverWait(driver, 5)
        # Africa, Middle East, and India
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bahrain)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bahrain)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bahrain_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bahrain_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Botswana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Botswana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cameroun)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cameroun)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Republique_Centrafricaine)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Republique_Centrafricaine)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cote_d_Ivoire)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cote_d_Ivoire)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Egypt)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Egypt)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Egypt_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Egypt_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinea_Bissau)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinea_Bissau)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinee)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinee)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinee_Equatoriale)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinee_Equatoriale)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_India)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_India)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Israel)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Israel)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jordan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jordan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jordan_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jordan_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kenya)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kenya)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kuwait)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kuwait)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kuwait_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kuwait_arab)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Madagascar)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Madagascar)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mali)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mali)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Maroc)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Maroc)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Maurice)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Maurice)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mozambique)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mozambique)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Niger)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Niger)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nigeria)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nigeria)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Oman)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Oman)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Oman_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Oman_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Qatar)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Qatar)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Qatar_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Qatar_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Saudi_Arabia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Saudi_Arabia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Saudi_Arabia_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Saudi_Arabia_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Senegal)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Senegal)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_South_Africa)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_South_Africa)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Tunisie)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Tunisie)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uganda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uganda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Arab_Emirates)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Arab_Emirates)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Arab_Emirates_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Arab_Emirates_arab)))
        time.sleep(2)
        print("Africa, Middle East, and India visible and clickable -  PASSED")

        # Asia Pacific
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Australia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Australia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_China_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_China_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hong_Kong)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hong_Kong)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hong_Kong_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hong_Kong_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Indonesia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Indonesia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Japan_ja)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Japan_ja)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Korea_ko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Korea_ko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Macao_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Macao_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Malaysia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Malaysia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_New_Zealand)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_New_Zealand)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Philippines)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Philippines)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Singapore)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Singapore)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Taiwan_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Taiwan_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Thailand_th)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Thailand_th)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Vietnam_vi)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Vietnam_vi)))
        time.sleep(2)
        print("Asia Pacific visible and clickable -  PASSED")

        # Europe
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Armenia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Armenia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Azerbaijan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Azerbaijan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belarus)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belarus)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belgie)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belgie)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belgique)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belgique)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bulgary)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bulgary)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cesko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cesko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Danmark)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Danmark)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Deutschland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Deutschland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Eesti)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Eesti)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Espana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Espana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_France)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_France)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Georgia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Georgia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Greece)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Greece)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hrvatska)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hrvatska)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ireland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ireland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Italia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Italia)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kazakhstan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kazakhstan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kyrgyzstan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kyrgyzstan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Latvija)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Latvija)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Liechtenstein)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Liechtenstein)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Lietuva)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Lietuva)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Luxembourg)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Luxembourg)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Magyarorszag)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Magyarorszag)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Malta)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Malta)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Moldova)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Moldova)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Montenegro)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Montenegro)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nederland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nederland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_North_Macedonia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_North_Macedonia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Norge)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Norge)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Osterreich)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Osterreich)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Polska)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Polska)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Portugal)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Portugal)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Romania)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Romania)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Russia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Russia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Slovensko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Slovensko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Slovenia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Slovenia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Schweiz)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Schweiz)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suisse)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suisse)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suomi)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suomi)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Sverige)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Sverige)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Tajikistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Tajikistan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turkiye)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turkiye)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turkmenistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turkmenistan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Kingdom)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Kingdom)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ukraine)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ukraine)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uzbekistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uzbekistan)))
        print("Europe is visible and clickable -  PASSED")
        time.sleep(2)

        # Latin America and the Caribbean
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Anguilla)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Anguilla)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Antigua_Barbuda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Antigua_Barbuda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Argentina)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Argentina)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Barbados)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Barbados)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belize)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belize)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bermuda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bermuda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bolivia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bolivia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Brasil)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Brasil)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_British_Virgin_Islands)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_British_Virgin_Islands)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cayman_Islands)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cayman_Islands)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Chile)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Chile)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Colombia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Colombia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Costa_Rica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Costa_Rica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Dominica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Dominica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Republica_Dominicana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Republica_Dominicana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ecuador)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ecuador)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_El_Salvador)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_El_Salvador)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Grenada)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Grenada)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guatemala)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guatemala)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guyana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guyana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Honduras)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Honduras)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jamaica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jamaica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mexico)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mexico)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Montserrat)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Montserrat)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nicaragua)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nicaragua)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Panama)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Panama)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Paraguay)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Paraguay)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Peru)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Peru)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Kitts_Nevis)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Kitts_Nevis)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Lucia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Lucia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Vincent_The_Grenadines)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Vincent_The_Grenadines)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suriname)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suriname)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_The_Bahamas)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_The_Bahamas)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Trinidad_Tobago)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Trinidad_Tobago)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turks_Caicos)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turks_Caicos)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uruguay)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uruguay)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Venezuela)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Venezuela)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_America_Latina_y_el_Caribe_Es)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_America_Latina_y_el_Caribe_Es)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Latin_America_and_the_Caribbean_Eng)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Latin_America_and_the_Caribbean_Eng)))
        time.sleep(2)

        # The United States, Canada, and Puerto Rico
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Canada_English)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Canada_English)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Canada_Francais)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Canada_Francais)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Puerto_Rico_English)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Puerto_Rico_English)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Puerto_Rico_Espanol)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Puerto_Rico_Espanol)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.United_States)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.United_States)))
        time.sleep(2)
class EdgeSearch(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Edge()
        self.driver.maximize_window()

    #Check that the current url is correct

        driver2 = self.driver
        driver2.get(hp.url)
        time.sleep(2)

        # Random delay function:
        def delay():
            time.sleep(random.randint(1, 5))
            delay()

        Apple_Expected_Url = hp.url
        current_url = driver2.current_url
        if current_url == Apple_Expected_Url:
            print("The currect URL is correct:", driver2.current_url)
        else:
            print("The current url is error:", driver2.current_url)

        # Check that the Apple title is correct
        Apple_Expected_Title = "Apple"
        current_title = driver2.title
        if Apple_Expected_Title == current_title:
            print("The Apple TITLE is correct:", driver2.title)
        else:
            print("The Apple TITLE is error:", driver2.title)

    def test_Africa_Middle_East_and_India(self):
        driver = self.driver
        driver.maximize_window()
        driver.get(hp.url)
        time.sleep(2)
        wait = WebDriverWait(driver, 5)
        # Africa, Middle East, and India
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bahrain)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bahrain)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bahrain_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bahrain_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Botswana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Botswana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cameroun)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cameroun)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Republique_Centrafricaine)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Republique_Centrafricaine)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cote_d_Ivoire)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cote_d_Ivoire)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Egypt)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Egypt)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Egypt_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Egypt_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinea_Bissau)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinea_Bissau)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinee)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinee)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guinee_Equatoriale)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guinee_Equatoriale)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_India)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_India)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Israel)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Israel)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jordan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jordan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jordan_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jordan_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kenya)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kenya)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kuwait)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kuwait)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kuwait_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kuwait_arab)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Madagascar)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Madagascar)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mali)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mali)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Maroc)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Maroc)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Maurice)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Maurice)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mozambique)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mozambique)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Niger)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Niger)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nigeria)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nigeria)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Oman)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Oman)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Oman_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Oman_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Qatar)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Qatar)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Qatar_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Qatar_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Saudi_Arabia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Saudi_Arabia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Saudi_Arabia_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Saudi_Arabia_arab)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Senegal)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Senegal)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_South_Africa)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_South_Africa)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Tunisie)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Tunisie)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uganda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uganda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Arab_Emirates)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Arab_Emirates)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Arab_Emirates_arab)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Arab_Emirates_arab)))
        time.sleep(2)
        print("Africa, Middle East, and India visible and clickable -  PASSED")

        # Asia Pacific
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Australia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Australia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_China_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_China_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hong_Kong)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hong_Kong)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hong_Kong_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hong_Kong_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Indonesia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Indonesia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Japan_ja)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Japan_ja)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Korea_ko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Korea_ko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Macao_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Macao_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Malaysia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Malaysia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_New_Zealand)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_New_Zealand)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Philippines)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Philippines)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Singapore)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Singapore)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Taiwan_zh)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Taiwan_zh)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Thailand_th)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Thailand_th)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Vietnam_vi)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Vietnam_vi)))
        time.sleep(2)
        print("Asia Pacific visible and clickable -  PASSED")

        # Europe
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Armenia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Armenia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Azerbaijan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Azerbaijan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belarus)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belarus)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belgie)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belgie)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belgique)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belgique)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bulgary)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bulgary)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cesko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cesko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Danmark)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Danmark)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Deutschland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Deutschland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Eesti)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Eesti)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Espana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Espana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_France)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_France)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Georgia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Georgia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Greece)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Greece)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Hrvatska)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Hrvatska)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ireland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ireland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Italia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Italia)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kazakhstan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kazakhstan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Kyrgyzstan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Kyrgyzstan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Latvija)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Latvija)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Liechtenstein)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Liechtenstein)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Lietuva)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Lietuva)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Luxembourg)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Luxembourg)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Magyarorszag)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Magyarorszag)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Malta)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Malta)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Moldova)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Moldova)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Montenegro)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Montenegro)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nederland)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nederland)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_North_Macedonia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_North_Macedonia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Norge)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Norge)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Osterreich)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Osterreich)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Polska)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Polska)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Portugal)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Portugal)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Romania)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Romania)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Russia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Russia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Slovensko)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Slovensko)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Slovenia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Slovenia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Schweiz)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Schweiz)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suisse)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suisse)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suomi)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suomi)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Sverige)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Sverige)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Tajikistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Tajikistan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turkiye)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turkiye)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turkmenistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turkmenistan)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_United_Kingdom)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_United_Kingdom)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ukraine)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ukraine)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uzbekistan)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uzbekistan)))
        print("Europe is visible and clickable -  PASSED")
        time.sleep(2)

        # Latin America and the Caribbean
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Anguilla)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Anguilla)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Antigua_Barbuda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Antigua_Barbuda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Argentina)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Argentina)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Barbados)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Barbados)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Belize)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Belize)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bermuda)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bermuda)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Bolivia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Bolivia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Brasil)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Brasil)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_British_Virgin_Islands)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_British_Virgin_Islands)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Cayman_Islands)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Cayman_Islands)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Chile)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Chile)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Colombia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Colombia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Costa_Rica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Costa_Rica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Dominica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Dominica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Republica_Dominicana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Republica_Dominicana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Ecuador)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Ecuador)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_El_Salvador)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_El_Salvador)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Grenada)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Grenada)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guatemala)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guatemala)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Guyana)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Guyana)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Honduras)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Honduras)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Jamaica)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Jamaica)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Mexico)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Mexico)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Montserrat)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Montserrat)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Nicaragua)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Nicaragua)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Panama)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Panama)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Paraguay)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Paraguay)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Peru)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Peru)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Kitts_Nevis)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Kitts_Nevis)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Lucia)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Lucia)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_St_Vincent_The_Grenadines)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_St_Vincent_The_Grenadines)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Suriname)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Suriname)))
        time.sleep(2)
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_The_Bahamas)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_The_Bahamas)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Trinidad_Tobago)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Trinidad_Tobago)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Turks_Caicos)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Turks_Caicos)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Uruguay)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Uruguay)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Venezuela)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Venezuela)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_America_Latina_y_el_Caribe_Es)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_America_Latina_y_el_Caribe_Es)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.country_Latin_America_and_the_Caribbean_Eng)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.country_Latin_America_and_the_Caribbean_Eng)))
        time.sleep(2)

        # The United States, Canada, and Puerto Rico
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Canada_English)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Canada_English)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Canada_Francais)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Canada_Francais)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Puerto_Rico_English)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Puerto_Rico_English)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.Puerto_Rico_Espanol)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.Puerto_Rico_Espanol)))
        wait.until(EC.visibility_of_element_located((By.XPATH, hp.United_States)))
        wait.until(EC.element_to_be_clickable((By.XPATH, hp.United_States)))
        time.sleep(2)

    def tearDown(self):
        self.driver.quit()
